### ISSUE TITLE
Refactor and upgrade Data Pack to include certain core features

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/itheumcore#11]
- Refactor Data PACK out of Data DEX (rename)
- Allow for delete of data pack (if no access is given)
- Contract returns count of how many plp have access to a datapackID
- Marketplace fee collection (local implementation ) 
- Write base unit tests for Data Pack contract

**Comment by newbreedofgeek** [comment]
https://github.com/Itheum/itheumcore/blob/feature/%2311-add-fees-dataPack/contracts/dataPack.sol#L79 seems duplicate of https://github.com/Itheum/itheumcore/blob/feature/%2311-add-fees-dataPack/contracts/dataPack.sol#L65

Do we need both?

---

**Comment by 0xpeho** [comment]
> https://github.com/Itheum/itheumcore/blob/feature/%2311-add-fees-dataPack/contracts/dataPack.sol#L79 seems duplicate of https://github.com/Itheum/itheumcore/blob/feature/%2311-add-fees-dataPack/contracts/dataPack.sol#L65
> 
> Do we need both?

Really good point. No, we don't. This came in due to merging. I refactored it.
